spring:
  application:
    name: merge-orchestrator-server

  cloud:
    function:
      definition: consumeNotification
    stream:
      bindings:
        consumeNotification-in-0:
          destination: case.import
        publishMerge-out-0:
          destination: merge
      source: publishMerge

network-store-server:
  preloading-strategy: COLLECTION

dbName: merge_orchestrator

logging:
  level:
    ROOT: INFO

parameters:
  tsos: FR,ES,PT
  process: SWE
  run-balances-adjustment: false

