spring:
  application:
    name: merge-orchestrator-server

  cloud:
    function:
      definition: consumeNotification
    stream:
      bindings:
        consumeNotification-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import
          group: mergeOrchestratorCaseImportGroup
          consumer:
            concurrency: 2
        publishMerge-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}merge
      output-bindings: publishMerge-out-0

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION

powsybl-ws:
  database:
    name: merge_orchestrator
