spring:
  application:
    name: merge-orchestrator-server

  cloud:
    function:
      definition: consumeNotification
    stream:
      bindings:
        consumeNotification-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}case.import
        publishMerge-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}merge
      source: publishMerge

network-store-server:
  preloading-strategy: COLLECTION

dbName: merge_orchestrator
