server:
  port: 5020

  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    case-server:
      base-uri: http://localhost:5000
    network-conversion-server:
      base-uri: http://localhost:5003
    network-store-server:
      base-uri: http://localhost:8080/

gridsuite:
  services:
    balances-adjustment-server:
      base-uri: http://localhost:5010
    loadflow-server:
      base-uri: http://localhost:5008
    case-validation-server:
      base-uri: http://localhost:5011
    cgmes-boundary-server:
      base-uri: http://localhost:5021
    report-server:
      base-uri: http://localhost:5028
