server:
  port: 5020

  rabbitmq:
    addresses: localhost

backing-services:
  case-server:
    base-uri: http://localhost:5000
  balances-adjustment-server:
    base-uri: http://localhost:5010
  loadflow-server:
    base-uri: http://localhost:5008
  case-validation-server:
    base-uri: http://localhost:5011
  cgmes-boundary-server:
    base-uri: http://localhost:5021
  network-conversion:
    base-uri: http://localhost:5003
  report-server:
    base-uri: http://localhost:5028

network-store-server:
  base-uri: http://localhost:8080/
